# Generated by Django 3.0.8 on 2020-07-26 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge_text', models.CharField(max_length=512)),
                ('co2_formula', models.CharField(blank=True, max_length=128, null=True)),
                ('water_formula', models.CharField(blank=True, max_length=128, null=True)),
                ('waste_formula', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeQuestion',
            fields=[
                ('question_id', models.SlugField(primary_key=True, serialize=False)),
                ('answer_input_type', models.CharField(choices=[('numeric', 'numeric'), ('select', 'select')], max_length=32)),
                ('answer_input_type_options', models.CharField(blank=True, help_text='Add additional input options used to further constrain allowed input values.', max_length=128, null=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.Pledge')),
            ],
        ),
        migrations.CreateModel(
            name='UserPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=512, null=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.Pledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'pledge')},
            },
        ),
        migrations.CreateModel(
            name='SelectAnswerFormulaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=64)),
                ('formula_value', models.FloatField()),
                ('pledge_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.PledgeQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserPledgeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=64)),
                ('formula_value', models.FloatField(blank=True)),
                ('pledge_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.PledgeQuestion')),
                ('user_pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pledges.UserPledge')),
            ],
            options={
                'unique_together': {('user_pledge', 'pledge_question')},
            },
        ),
    ]
