# Generated by Django 3.0.8 on 2020-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='co2_impact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='waste_impact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pledge',
            name='water_impact',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
